# Generated by Django 5.1 on 2024-08-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(default='Не указано', max_length=255),
        ),
    ]
